[package]
name = "webbase"
version = "0.1.0"
edition = "2018"

[dependencies]
clap = "2"
tokio = { version = "1", features = ["macros"] }
reqwest = { version = "0.11", features = ["blocking"] }
tl = "0.4"